import product1 from "./assets/1.jpg";
import product2 from "./assets/2.jpg";
import product3 from "./assets/3.jpg";
import product4 from "./assets/4.jpg";
import product5 from "./assets/5.jpg";
import product6 from './assets/6.png';
import product7 from './assets/7.png';
import product8 from './assets/8.png';
import product9 from './assets/9.png';
import product10 from './assets/10.png';
import product11 from './assets/11.png';
import product12 from './assets/12.png';
import product13 from './assets/13.png';
import product14 from './assets/14.png';
import product16 from './assets/16.png';
import product18 from './assets/18.png';
import product19 from './assets/19.png';


export const products = [{
            id:'1',    
            name:'white Tshirt',price:'$329.99', type:'leather',
              size:'S', image:product1, color:'white', outerLayer:'polyster 100%', 
              linning:'nylon 82%, elastane 8%, polyester 10%',
              interior: 'grey duck down 80%, feather 20%', 
              filling: '100% Certified recycled feather and down', 
              washinginfo:['Machine Wash Up to 30C / 86F Gentle Cycle', 'Do not Bleach', 'Iron Up To 100C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']}, 
          {id:'2',
            name:'Regular Fit Needlecord Shirt',price:'$29.99', type:'cotton',
          size:'S', color:'grey', outerLayer:'cotton 100%', 
          linning:'',
          image:product2,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'3',name:'Sweater',price:'$29.99', type:'cotton',
          size:'S', color:'blue', outerLayer:'cotton 100%', 
          linning:'',
          image:product3,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'4',name:'Reguar Tucker Jacket',price:'$99.99', type:'cotton',
          size:'S', color:'brown', outerLayer:'cotton 100%', 
          linning:'',
          image:product4,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'5',name:'Regular Tucker Jacket',price:'$99.99', type:'cotton',
          size:'S', color:'brown', outerLayer:'cotton 100%', 
          linning:'',
          image:product5,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'6',name:'Jeans Denim',price:'$79.99', type:'denim',
          size:'S', color:'brown', outerLayer:'cotton 100%', 
          linning:'',
          image:product6,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'7',name:'Denim Shirt',price:'$39.99', type:'cotton',
          size:'S', color:'brown', outerLayer:'cotton 100%', 
          linning:'',
          image:product8,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'8',name:'Green outerwear Jacket',price:'$19.99', type:'cotton',
          size:'S', color:'brown', outerLayer:'cotton 100%', 
          linning:'',
          image:product10,
          interior: '', 
          filling: '', 
          otherinfo: 'White Jacket',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'9',name:'White Denim Jacket',price:'$59.99', type:'denim',
          size:'S', color:'white', outerLayer:'cotton 100%', 
          linning:'',
          image:product13,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'10',name:'Green Oak Jacket',price:'$99.99', type:'denim',
          size:'S', color:'green', outerLayer:'cotton 100%', 
          linning:'',
          image:product14,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'11',name:'Puffer Jacket',price:'$79.99', type:'denim',
          size:'M', color:'blue and orange', outerLayer:'cotton 100%', 
          linning:'',
          image:product16,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'12',name:'Marron Denim Jacket',price:'$99.99', type:'denim',
          size:'S', color:'maroon', outerLayer:'cotton 100%', 
          linning:'',
          image:product18,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']},
          {id:'13',name:'Red Sweater',price:'$59.99', type:'wool',
          size:'M', color:'red', outerLayer:'cotton 100%', 
          linning:'',
          image:product19,
          interior: '', 
          filling: '', 
          otherinfo: 'Needlecord fabric. Made of 100% cotton. Regular fit. Oxford Collar',
          care:['Machine Wash Up to 30C / 86F Gentle Cycle', 
          'Do not Bleach', 'Iron Up To 110C/230F', 'Do Not Dry Clean', 'Do Not Tumble Dry']}
        ];
//export default products;